#%RAML 1.0
title: ExampleAPI
version: v1.0
baseUri: api/v1/

description: |
  This is an API definition for a proof of concept project I'm developing.
  Consists on a very basic CRUD API for cars.
  No authorisation applied for now.

types: !include schemas/types.raml

/cars:
  post:
    description: Operation to add a car to the system.
    body:
      application/json:
        type: Car
    responses:
      201:
        description: Car sucessfully created.
      405:
        description: Invalid car input.
      422:
        description: Invalid values for car properties.
  /{carId}:
    description: Car external identifier.
  get:
    description: Operation to retrieve a car by its id.
    responses:
      200:
        description: Car sucessfully retrieved.
      405:
        description: Invalid id format. Bad request
      404:
        description: Car not found.
  put:
    description: Operation to update a car object entirely.
    body:
      application/json:
        type: Car
    responses:
      200:
        description: Car sucessfully updated.
        body:
          application/json:
            type: Car
      405:
        description: Invalid car input.
      422:
        description: Invalid values for car properties.
  patch:
    description: Operation to update a car object partially.
    body:
      application/json:
        type: object
        description: Set of car properties to be updated.
        example: |
          {
            "color": "red",
            "lastMOT": "2011-12-03T10:15:30"
          }
    responses:
      200:
        description: Car sucessfully updated.
        body:
          application/json:
            type: Car
      405:
        description: Invalid car input.
      422:
        description: Invalid values for car properties.
  delete:
    description: Operation to delete a car object.
    responses:
      204:
        description: Car sucessfully deleted
      404:
        description: Car not found.
      405:
        description: Invalid id format. Bad request
