endpoints:
  sensitive: false

info:
  app:
    name: Car Management Microservice
    description: This is a sample project to proof microservices architecture concepts and best practises.
    version: @project.version@


